# Will have docker access
lyoko_user: "seith"

# Email needed for Let's Encrypt SSL Certs
lyoko_user_email: "lyoko@seith.cloud"

# Domain used by Lyoko
lyoko_domain: seith.cloud

# Lyoko directory
lyoko_directory: "/lyoko"

# Apps directory
apps_directory: "/lyoko/apps"
