---
- name: Start Wizarr
  when: wizarr_enabled is true
  block:
    - name: Create Wizarr Directory
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: "0755"
      with_items:
        - "{{ wizarr_config_directory }}"

    - name: Create Wizarr Docker Container
      community.docker.docker_container:
        name: "{{ wizarr_container_name }}"
        image: "{{ wizarr_image_name }}:{{ wizarr_image_version }}"
        volumes:
          - "{{ wizarr_config_directory }}:/data"
        env:
          TZ: "{{ core_timezone }}"
          PUID: "{{ wizarr_puid }}"
          PGID: "{{ wizarr_pgid }}"
          DISABLE_BUILTIN_AUTH: "{{ wizarr_disable_builtin_auth }}"
        networks:
          - name: "proxy"
        pull: true
        restart_policy: unless-stopped
        labels:
          traefik.enable: "true"
          traefik.http.routers.wizarr.rule: "Host(`{{ wizarr_domain }}.{{ lyoko_domain }}`)"
          traefik.http.routers.wizarr.entrypoints: "websecure"
          traefik.http.routers.wizarr.tls.certresolver: "cloudflare"
          traefik.http.services.wizarr.loadbalancer.server.port: "5690"
          traefik.docker.network: "proxy"
